### ISSUE TITLE
Does it support Android?

### ISSUE THREAD

**Issue by yangjunsss** [eyaleizenberg/react-native-floating-label-text-input#16]
I make a try on Android platform, it can't represent the value of filed.

**Comment by DeveloperAlly** [comment]
DOES NOT work on android = useless component for cross platform language

**Comment by athmangude** [comment]
@AlisonWonderlandApps That's mean

**Comment by eyaleizenberg** [comment]
@AlisonWonderlandApps @yangjunsss  You are more than welcomed to contribute and add android support.
