### ISSUE TITLE
add defaultValue prop

### ISSUE THREAD

**Issue by jakenewby** [eyaleizenberg/react-native-floating-label-text-input#2]
I understand that `onChangeTextValue` allows you to manage a piece of state that will provide similar functionality to this.  Was omitting a `defaultValue` prop purely a design decision? If not, I'd love to see this implemented just as it is in react-native's `TextInput` component.  Thanks!

**Comment by kristianmandrup** [comment]
Looking at the code:

``` js
            <TextFieldHolder withValue={this.state.text}>
              <TextInput
                placeholder={this.props.placeHolder}
                style={[styles.valueText]}
                value={this.state.text}
                onFocus={this.setFocus}
                onBlur={this.unsetFocus}
                onChangeText={this.setText}
                secureTextEntry={this.props.secureTextEntry}
                keyboardType={this.props.keyboardType}
              />
            </TextFieldHolder>
```

You could just add:

`<TextInput defaultValue={this.props.defaultValue}` 

I would assume!?

**Comment by kristianmandrup** [comment]
For me it doesn't render ANYTHING that I can see :(

**Comment by eyaleizenberg** [comment]
@jakenewby What @kristianmandrup would work. However, a better idea would be to change the TextInput to pass all the props without having to specify each one (there is another issue on a different attribute). Would one of you be willing to open a PR for that?

**Comment by jakenewby** [comment]
Opened a PR @ https://github.com/eyaleizenberg/react-native-floating-label-text-input/pull/8
