### ISSUE TITLE
Changing font size and font family of the input?

### ISSUE THREAD

**Issue by zakster12** [eyaleizenberg/react-native-floating-label-text-input#25]
Hello and thank you for the great component! It works perfectly and I do not have any issues with it. I just would like to ask how I can change the font size and the font family of the input?

*P.S: It's not a bug but a question which I couldn't find in the documentation.

Thank you again!

**Comment by eyaleizenberg** [comment]
@zakster12 thanks for the kind words. At the moment the component does not support this, however, you could easily extend it and open a pull request to this repo.
