### ISSUE TITLE
option for a multiline textarea input?

### ISSUE THREAD

**Issue by joshbedo** [eyaleizenberg/react-native-floating-label-text-input#3]

**Comment by zh-wowtv** [comment]
+1

**Comment by eyaleizenberg** [comment]
I'm not really sure how this will work. If one of you wants to give it a go and open a PR, that would be great. Until then, I am closing this as I have no time to work on that.

**Comment by srhise** [comment]
SOLVED: https://facebook.github.io/react-native/docs/textinput.html

`<TextInput
              multiline = {true}
              numberOfLines = {4}
          />`

**Comment by lavarajallu** [comment]
@srhise this is not getting like this  i want like this below text Input 
![screen shot 2018-07-05 at 1 24 23 pm](https://user-images.githubusercontent.com/20550556/42309648-d0c59aea-8056-11e8-8b59-50b14371513e.png)
